const books = [
    {
        id: 1,
        title: "Belajar JavaScript Dasar",
        author: "Andi Prasetyo",
        year: 2021,
        description: "Panduan lengkap untuk pemula yang ingin belajar JavaScript dari nol.",
        image: "https://example.com/images/belajar-javascript-dasar.jpg",
    },
    {
        id: 2,
        title: "React untuk Pemula",
        author: "Dina Sari",
        year: 2022,
        description: "Mengenal konsep dan praktik membuat aplikasi React modern.",
        image: "https://example.com/images/react-untuk-pemula.jpg",
    },
    {
        id: 3,
        title: "The Lord of the Rings",
        author: "John Ronald Reuel Tolkien",
        year: 1954,
        description: "Seorang hobbit, Frodo Baggins, mengemban tugas melintasi Middle-earth untuk menghancurkan Cincin Sauron yang mampu mendominasi seluruh dunia.",
        image: "https://example.com/images/the-lord-of-the-rings.jpg",
    },
    {
        id: 4,
        title: "The Hobbit",
        author: "John Ronald Reuel Tolkien",
        year: 1937,
        description: "Menceritakan perjalanan seorang hobbit, Bilbo Baggins, dan sekelompok kurcaci yang berusaha merebut kembali harta karun mereka dari cengkeraman naga Smaug yang berbahaya.",
        image: "https://example.com/images/the-hobbit.jpg",
    },
    {
        id: 5,
        title: "The Hitchhiker's Guide to the Galaxy",
        author: "Douglas Adams",
        year: 1979,
        description: "Perjalanan seorang pria Bumi di luar angkasa setelah planetnya dihancurkan untuk pembangunan jalan tol antar-galaksi.",
        image: "https://example.com/images/the-hitchhikers-guide-to-the-galaxy.jpg",
    },
    {
        id: 6,
        title: "Dune",
        author: "Frank Herbert",
        year: 1965,
        description: "Kisah tentang Paul Atreides, pewaris sebuah keluarga bangsawan yang mengelola planet gurun Arrakis, satu-satunya sumber rempah-rempah yang berharga di alam semesta.",
        image: "https://example.com/images/dune.jpg",
    },
    {
        id: 7,
        title: "1984",
        author: "George Orwell",
        year: 1949,
        description: "Sebuah novel distopia yang menggambarkan masyarakat totalitarian di mana pemerintah mengendalikan setiap aspek kehidupan, termasuk pemikiran warganya.",
        image: "https://example.com/images/1984.jpg",
    },
    {
        id: 8,
        title: "Pride and Prejudice",
        author: "Jane Austen",
        year: 1813,
        description: "Novel roman tentang kisah cinta antara Elizabeth Bennet, seorang wanita cerdas yang berjiwa bebas, dan Mr. Darcy, seorang bangsawan kaya yang sombong.",
        image: "https://example.com/images/pride-and-prejudice.jpg",
    },
    {
        id: 9,
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        year: 1960,
        description: "Kisah tentang seorang pengacara di era Depresi Besar yang membela seorang pria kulit hitam yang dituduh melakukan kejahatan yang tidak dilakukannya.",
        image: "https://example.com/images/to-kill-a-mockingbird.jpg",
    },
    {
        id: 10,
        title: "Laskar Pelangi",
        author: "Andrea Hirata",
        year: 2005,
        description: "Buku ini mengisahkan perjuangan sepuluh anak miskin di sebuah desa terpencil di Belitung untuk mendapatkan pendidikan yang layak.",
        image: "https://example.com/images/laskar-pelangi.jpg",
    },
];

export default books;